plugins-bad/dcsctp: fix potential undefined behavior in sctp_socket_send by handling empty payloads explicitly
- Replace vector range constructor with explicit assign and empty check
- Avoid constructing std::vector from empty or invalid ranges
- Prevents compiler error and undefined behavior due to invalid pointer deletion

Reported by gcc as:
```
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = unsigned char]’,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = unsigned char]’ at /opt/gcc-future/include/c++/14.3.0/bits/alloc_traits.h:550:23,
    inlined from ‘std::vector<_Tp, _Alloc>::_M_realloc_append(_Args&& ...)::_Guard::~_Guard() [with _Args = {unsigned char}; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/vector.tcc:616:18,
    inlined from ‘void std::vector<_Tp, _Alloc>::_M_realloc_append(_Args&& ...) [with _Args = {unsigned char}; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/vector.tcc:688:7,
    inlined from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {unsigned char}; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/vector.tcc:123:21,
    inlined from ‘void std::vector<_Tp, _Alloc>::push_back(value_type&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/stl_vector.h:1314:21,
    inlined from ‘SctpSocket_SendStatus sctp_socket_send(SctpSocket*, const uint8_t*, size_t, uint16_t, uint32_t, bool, int32_t*, size_t*)’ at /opt/gstreamer/subprojects/gst-plugins-bad/ext/sctp/dcsctp/sctpsocket.cc:400:31:
/opt/gcc-future/include/c++/14.3.0/bits/new_allocator.h:172:33: error: ‘void operator delete(void*, std::size_t)’ called on pointer ‘<unknown>’ with nonzero offset [1, 9223372036854775807] [-Werror=free-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
In member function ‘_Tp* std::__new_allocator<_Tp>::allocate(size_type, const void*) [with _Tp = unsigned char]’,
    inlined from ‘static _Tp* std::allocator_traits<std::allocator<_CharT> >::allocate(allocator_type&, size_type) [with _Tp = unsigned char]’ at /opt/gcc-future/include/c++/14.3.0/bits/alloc_traits.h:515:28,
    inlined from ‘std::_Vector_base<_Tp, _Alloc>::pointer std::_Vector_base<_Tp, _Alloc>::_M_allocate(std::size_t) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/stl_vector.h:383:33,
    inlined from ‘void std::vector<_Tp, _Alloc>::_M_range_initialize_n(_Iterator, _Iterator, size_type) [with _Iterator = const unsigned char*; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/stl_vector.h:1716:23,
    inlined from ‘void std::vector<_Tp, _Alloc>::_M_range_initialize(_ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const unsigned char*; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/stl_vector.h:1705:25,
    inlined from ‘std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = const unsigned char*; <template-parameter-2-2> = void; _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /opt/gcc-future/include/c++/14.3.0/bits/stl_vector.h:724:23,
    inlined from ‘SctpSocket_SendStatus sctp_socket_send(SctpSocket*, const uint8_t*, size_t, uint16_t, uint32_t, bool, int32_t*, size_t*)’ at /opt/gstreamer/subprojects/gst-plugins-bad/ext/sctp/dcsctp/sctpsocket.cc:393:57:
/opt/gcc-future/include/c++/14.3.0/bits/new_allocator.h:151:55: note: returned from ‘void* operator new(std::size_t)’
  151 |         return static_cast<_Tp*>(_GLIBCXX_OPERATOR_NEW(__n * sizeof(_Tp)));
      |                                                       ^
cc1plus: all warnings being treated as errors
```